import { emptyProject, type Project, type Workspace } from "@repo/registry";
const ago = (hours: number) =>
  new Date(Date.now() - hours * 3600000).toISOString();
export function demoWorkspace(): Workspace {
  const rows = [
    [
      "1",
      "Fieldnotes",
      "A home for ideas, reading notes, and everything worth keeping.",
      "live",
      "operational",
      "Next.js,TypeScript,PostgreSQL",
      "Cloudflare",
      2,
      "Finish the collection sharing flow.",
    ],
    [
      "2",
      "Invoice studio",
      "Simple invoicing for independent work.",
      "building",
      "degraded",
      "React,Python,FastAPI",
      "Docker · Windows",
      8,
      "Investigate the API timeout, then finish PDF exports.",
    ],
    [
      "3",
      "Home archive",
      "An organised library for family photos and documents.",
      "live",
      "operational",
      "Vue,Node.js,SQLite",
      "Docker · Mac",
      26,
      "Review the backup retention settings.",
    ],
    [
      "4",
      "Weekend atlas",
      "A small guide to places we want to explore.",
      "paused",
      "unknown",
      "Astro,TypeScript",
      "Vercel",
      192,
      "Pick this up when the next trip is booked.",
    ],
    [
      "5",
      "Reading room",
      "An experiment in quieter RSS reading.",
      "building",
      "unknown",
      "SvelteKit,PostgreSQL",
      "Local · Mac",
      72,
      "Connect feed discovery to the onboarding screen.",
    ],
    [
      "6",
      "Pocket weather",
      "A focused weather widget for the desktop.",
      "completed",
      "operational",
      "Go,React",
      "Fly.io",
      380,
      "No outstanding work.",
    ],
  ] as const;
  const projects: Project[] = rows.map(
    ([
      id,
      name,
      description,
      lifecycle,
      health,
      stack,
      provider,
      hours,
      nextAction,
    ]) => ({
      ...emptyProject(),
      id,
      name,
      slug: name.toLowerCase().replaceAll(" ", "-"),
      description,
      lifecycle,
      health,
      organisation: "Personal",
      stack: stack
        .split(",")
        .map((name) => ({ name, category: "technology", source: "Demo data" })),
      resources: [],
      deployments: [
        {
          id: `d-${id}`,
          name: "Primary deployment",
          environment: provider.includes("Local") ? "local" : "production",
          provider,
          url: "",
          dashboardUrl: "",
          machineId: "",
          localPath: "",
          expectedRunning: true,
        },
      ],
      nextAction,
      createdAt: ago(800),
      updatedAt: ago(hours),
      lastWorkedAt: ago(hours),
      coverage: {
        total: health === "unknown" ? 0 : 2,
        fresh: health === "unknown" ? 0 : 2,
        stale: 0,
      },
    }),
  );
  return {
    projects,
    user: "Demo workspace",
    role: "viewer",
    mode: "demo",
    githubConfigured: false,
    collectors: [
      {
        id: "mac",
        name: "Mac workstation",
        platform: "darwin",
        lastSeenAt: ago(0.01),
        createdAt: ago(90),
        revokedAt: null,
        online: true,
      },
      {
        id: "windows",
        name: "Windows server",
        platform: "win32",
        lastSeenAt: ago(0.02),
        createdAt: ago(90),
        revokedAt: null,
        online: true,
      },
    ],
    incidents: [
      {
        id: "demo-incident",
        projectId: "2",
        projectName: "Invoice studio",
        checkId: "demo-check",
        title: "API response is slow",
        message: "The latest response exceeded the configured threshold.",
        createdAt: ago(0.2),
        resolvedAt: null,
      },
    ],
    activity: [
      {
        id: "a1",
        projectId: "1",
        actor: "You",
        action: "Handoff saved",
        detail: "Fieldnotes",
        createdAt: ago(2),
      },
      {
        id: "a2",
        projectId: "2",
        actor: "You",
        action: "Project updated",
        detail: "Invoice studio",
        createdAt: ago(8),
      },
      {
        id: "a3",
        projectId: "3",
        actor: "You",
        action: "Check added",
        detail: "Home archive",
        createdAt: ago(26),
      },
    ],
    monitor: {
      lastTickAt: ago(0.01),
      dueChecks: 0,
      activeChecks: 8,
      batchSize: 3,
    },
  };
}
