"use client";
import { useState } from "react";
import {
  Github,
  Upload,
  ArrowRight,
  FileJson,
  FolderSearch,
} from "lucide-react";
import type { ImportCandidate } from "@repo/registry";
import { candidateToProject } from "@repo/registry/discovery";
import { api } from "../../lib/api";
import { ErrorNotice, Field, Panel, Stack } from "./ui";
export default function ImportPanel({
  onClose,
  onSaved,
  notify,
}: {
  onClose: () => void;
  onSaved: () => void;
  notify: (s: string) => void;
}) {
  const [tab, setTab] = useState("github");
  const [repository, setRepository] = useState("");
  const [candidates, setCandidates] = useState<ImportCandidate[]>([]);
  const [selected, setSelected] = useState<number[]>([]);
  const [backup, setBackup] = useState<{
    format: string;
    version: number;
    items: unknown[];
  } | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  async function inspect(e: React.FormEvent) {
    e.preventDefault();
    setBusy(true);
    setError("");
    try {
      const candidate = await api<ImportCandidate>("/github/inspect", {
        method: "POST",
        body: JSON.stringify({ repository }),
      });
      setCandidates([candidate]);
      setSelected([0]);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }
  async function readFile(file: File | undefined) {
    if (!file) return;
    setError("");
    try {
      if (file.size > 500000)
        throw new Error("Choose a JSON file smaller than 500 KB.");
      const data = JSON.parse(await file.text());
      if (tab === "backup") {
        if (
          data.format !== "opsglass-inventory" ||
          data.version !== 1 ||
          !Array.isArray(data.items)
        )
          throw new Error("Choose an OpsGlass inventory export.");
        setBackup(data);
        return;
      }
      if (
        data.format !== "opsglass-discovery" ||
        !Array.isArray(data.candidates)
      )
        throw new Error(
          "Choose a JSON file generated by the OpsGlass scanner.",
        );
      const valid = data.candidates
        .slice(0, 100)
        .filter(
          (c: ImportCandidate) =>
            typeof c.name === "string" && Array.isArray(c.stack) && c.commands,
        );
      setCandidates(valid);
      setSelected(valid.map((_: unknown, i: number) => i));
    } catch (e) {
      setError((e as Error).message);
    }
  }
  async function importSelected() {
    setBusy(true);
    setError("");
    const completed: number[] = [];
    try {
      for (const i of selected) {
        const c = candidates[i];
        if (c) {
          await api("/projects", {
            method: "POST",
            body: JSON.stringify(candidateToProject(c)),
          });
          completed.push(i);
        }
      }
      notify(
        `${completed.length} project${completed.length === 1 ? "" : "s"} imported.`,
      );
      onSaved();
    } catch (e) {
      setSelected(selected.filter((i) => !completed.includes(i)));
      setError(
        `${completed.length} imported. ${(e as Error).message} Successful items have been deselected.`,
      );
    } finally {
      setBusy(false);
    }
  }
  async function restore() {
    setBusy(true);
    setError("");
    let done = 0;
    try {
      for (const item of backup!.items) {
        await api("/inventory/import", {
          method: "POST",
          body: JSON.stringify({ ...backup, items: [item] }),
        });
        done++;
      }
      notify(
        `${done} projects restored. Review hosting and enable checks when ready.`,
      );
      onSaved();
    } catch (e) {
      setBackup({ ...backup!, items: backup!.items.slice(done) });
      setError(`${done} restored. ${(e as Error).message}`);
    } finally {
      setBusy(false);
    }
  }
  return (
    <Panel
      title="Bring your projects together"
      subtitle="Review discovered details before adding them to your workspace."
      onClose={onClose}
      wide
    >
      <div className="tabs">
        {[
          ["github", "GitHub"],
          ["local", "Local discovery"],
          ["backup", "Restore inventory"],
        ].map(([id, label]) => (
          <button
            key={id}
            className={tab === id ? "active" : ""}
            onClick={() => {
              setTab(id!);
              setCandidates([]);
              setSelected([]);
              setError("");
              setBackup(null);
            }}
          >
            {label}
          </button>
        ))}
      </div>
      <div className="sheet-body">
        <ErrorNotice message={error} />
        {tab === "github" && (
          <form onSubmit={inspect}>
            <div className="import-intro">
              <Github size={30} />
              <div>
                <h3>Start with a repository</h3>
                <p>
                  Read manifests to identify frameworks, databases, and setup
                  commands.
                </p>
              </div>
            </div>
            <Field label="GitHub repository">
              <input
                autoFocus
                required
                value={repository}
                onChange={(e) => setRepository(e.target.value)}
                placeholder="https://github.com/owner/repository"
              />
            </Field>
            <button className="button primary" disabled={busy}>
              {busy ? "Reading repository…" : "Inspect repository"}
              <ArrowRight size={15} />
            </button>
          </form>
        )}
        {tab === "local" && (
          <>
            <div className="import-intro">
              <FolderSearch size={30} />
              <div>
                <h3>Discover projects on your computer</h3>
                <p>
                  Run the scanner on your Mac or Windows machine, then review
                  the resulting file here.
                </p>
              </div>
            </div>
            <pre className="scan-command">
              <code>
                node scripts/collector.mjs scan --root /path/to/projects
                --docker --output discoveries.json
              </code>
            </pre>
            <p className="muted small-text">
              The scan reads package manifests and Docker container metadata. It
              skips environment files, dependency folders, and symlinks. Nothing
              is uploaded until you import it.
            </p>
            <label className="file-drop">
              <Upload size={24} />
              <strong>Choose discoveries.json</strong>
              <span>A file from the OpsGlass local scanner</span>
              <input
                aria-label="Choose local discovery file"
                type="file"
                accept=".json,application/json"
                onChange={(e) => void readFile(e.target.files?.[0])}
              />
            </label>
          </>
        )}
        {tab === "backup" && (
          <>
            <div className="import-intro">
              <FileJson size={30} />
              <div>
                <h3>Restore an inventory export</h3>
                <p>
                  Creates new project records. Cloud checks start paused.
                  Register collectors again before recreating local checks.
                </p>
              </div>
            </div>
            <label className="file-drop">
              <Upload size={24} />
              <strong>Choose inventory export</strong>
              <span>Project records, cloud checks, and project memory</span>
              <input
                aria-label="Choose inventory backup"
                type="file"
                accept=".json,application/json"
                onChange={(e) => void readFile(e.target.files?.[0])}
              />
            </label>
            {backup && (
              <div className="restore-summary">
                <strong>{backup.items.length} projects ready to restore</strong>
                <button
                  className="button primary"
                  disabled={busy}
                  onClick={() => void restore()}
                >
                  {busy ? "Restoring…" : "Restore projects"}
                </button>
              </div>
            )}
          </>
        )}
        {candidates.length > 0 && (
          <div className="import-preview">
            <div className="section-heading">
              <h3>Review discoveries</h3>
              <span className="muted">{selected.length} selected</span>
            </div>
            {candidates.map((c, i) => (
              <label key={`${c.name}-${i}`} className="candidate">
                <input
                  type="checkbox"
                  checked={selected.includes(i)}
                  onChange={(e) =>
                    setSelected(
                      e.target.checked
                        ? [...selected, i]
                        : selected.filter((n) => n !== i),
                    )
                  }
                />
                <div>
                  <h3>{c.name}</h3>
                  <p>{c.description || c.localPath || c.repository}</p>
                  <Stack items={c.stack} />
                  {c.warnings?.map((w, i) => (
                    <small key={i}>{w}</small>
                  ))}
                </div>
              </label>
            ))}
            <p className="muted small-text">
              Discovered hosting configuration needs confirmation. Monitoring
              remains unconfigured until you add checks.
            </p>
          </div>
        )}
      </div>
      {candidates.length > 0 && (
        <div className="sheet-footer">
          <button className="button" onClick={onClose}>
            Cancel
          </button>
          <button
            className="button primary"
            disabled={busy || !selected.length}
            onClick={() => void importSelected()}
          >
            {busy
              ? "Importing…"
              : `Import ${selected.length} project${selected.length === 1 ? "" : "s"}`}
          </button>
        </div>
      )}
    </Panel>
  );
}
